apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lucashnrq/backend:v1 
          ports:
            - containerPort: 3001
          env:
            - name: DB_URL
              value: "mongodb://db:27017/vidly"
          command: ["./docker-entrypoint.sh"]
