apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mongo:4.0-xenial # imagem oficial do MongoDB
          ports:
            - containerPort: 27017 # porta padrão do MongoDB
          volumeMounts:
            - name: mongo-data 
              mountPath: /data/db  # caminho dentro do container onde os dados são salvos
      volumes:
        - name: mongo-data # volume a ser montado no container
          persistentVolumeClaim: # Ligação com o PVC (PersistentVolumeClaim)
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce # o volume pode ser montado em um nó por vez (modo padrão para MongoDB)
  resources:
    requests:
      storage: 1Gi
