apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: lucashnrq/frontend:v1
          ports:
            - containerPort: 3000
          env:
            # variável de ambiente passada para o React no build
            # como o React roda no navegador do usuário, ele precisa
            # do IP e porta pública (NodePort) do backend.
            - name: REACT_APP_API_URL
              value: "http://192.168.49.2:30011/api" # backend exposto pelo NodePort
