apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000        # porta interna do cluster
      targetPort: 3000  # porta do container
      nodePort: 30000   # 👈 coloca acima de 30000 (faixa reservada pro NodePort)
